### ISSUE TITLE
ADFS

### ISSUE THREAD

**Issue by galrotem1993** [nextcloud/user_saml#104]
Hi I am trying to config ADFS to work with my nextcloud server. 
I enabled the app and inserted all the information it needed but the ADFS server its self needs a url to the metadata.xml file on the nextcloud server however i cant find where it is saved i only found a url that downloads the file. 
I also tried to manually put the file in the main nextcloud folder but when i try to reach it via url i get a redirect to the login page.
How can i find the url i need/where the metadata.xml file is saved
Thanks in advance

**Comment by bne86** [comment]
Hi,
is https://<server>/index.php/apps/user_saml/saml/metadata what you are looking for?
When you go to "Admin"->"SSO & Saml..."you can copy the link from the "Download metadata XML" Button.
best

**Comment by galrotem1993** [comment]
Thank you but no this only downloads the file and i need a display of the file

**Comment by bne86** [comment]
Hi,
but thats the way it should work?
That he is downloading instead of displaying should be related to the fact that the content type is "text/xml" instead of "text/html", but the later one should not be required for a IDP that simply wants a XML.
We use [uity-idm](http://www.unity-idm.eu/) as identity provider, and configure it to fetch the metadata from the URL i already mentioned.
Also, if i take a look at a classical Apache2 user_shibboleth SP and not the php saml lib that user_saml uses, it generates a Metadata file that the client would download [e.g.](https://monitoring.clarin.eu/Shibboleth.sso/Metadata)
best
benedikt

**Comment by galrotem1993** [comment]
When i give the ADFS the url that you suggested (that downloads the file) and then browse to the nextcloud i recieve the following page:

invalid_response

Not authenticated

**Comment by bne86** [comment]
Browser (Safari), curl and wget are able to download the XML from the [link](https://fsd-cloud48.zam.kfa-juelich.de/index.php/apps/user_saml/saml/metadata) that i mentioned.

You mentioned that you are able to download the metadata file to, even if you expect your client to render instead of download it. ;)

Did you point your ADFS to "[my](https://fsd-cloud48.zam.kfa-juelich.de/index.php/apps/user_saml/saml/metadata)" link, or the link of your local nextcloud? You could try testing against my link, if there is the same issue i think something at the ADFS implementation is broken. Maybe it appends ".xml" to the link and then is redirected or so.
If my link works, maybe your nextcloud setup is in some way broken.

**Comment by bne86** [comment]
I think with my former comment i misunderstood your problem.

You configured SSO against ADFS and your nextcloud login no longer works and is showing "invalid_response"? Unfortunately i do not have ADFS available so someone else has to take over support here.

For additional support your concrete versions (nextcloud, user_saml) and your user_saml settings are required. E.g. which certificates did you configure etc.
