### ISSUE TITLE
using a parent service provider

### ISSUE THREAD

**Issue by julio1501** [nextcloud/user_saml#21]
would be a great idea to configure the app so that customer can use its own SP (ex. Shibboleth SP) . This is important forhosting multiple nextcloud  instances on a webserver . The webserver acts as  SP for all instances with  activated SAML functions.

**Comment by LukasReschke** [comment]
Thanks a lot for your feedback! 🚀 

So I assume there would be the following two authentication modes would make sense to support:

1. The current one where Nextcloud acts as SP
2. Another one where Nextcloud redirects to the SP that could be a locally installed mod_shib

In the second one this would mean that there is a single protected route such as `/saml-auth` or `/shibboleth` and that one would be protected on the web server layer. Everything else is open that allows us to keep most of the configuration and flexibility in our code base instead of the server config.

I suppose your SAML module then basically sets an environment variable? In that case we'd need:

1. A wizard that makes it easier to choose which mode to use and hide irrelevant fields (kinda related to https://github.com/nextcloud/user_saml/issues/18)
2. An input field to set which environment variable to use

Did I get that right? :-)

**Comment by julio1501** [comment]
you´ve got it! exactly what we need:-). Then  we have not always upload a separate metadata file to our idP.

**Comment by nordlolek** [comment]
Hi!

What is the status on a feature meantioned above? I'm really looking foward to be able to use external - parental SP (eg. simpleSAML, shibboleth,...) because we use federative SSO (structure is similar to: https://www.switch.ch/aai/about/federation/Federation_Structure.png ) . When our users are loging to service, they have to use discovery service to choose their idp so that SP is communicating with right idp. Current nexclouds user_saml app is unfortunately not enabling us such use.
