### ISSUE TITLE
SAML SSO Login with ADFS

### ISSUE THREAD

**Issue by sergiobaiao** [nextcloud/user_saml#553]
Hi there folks,

I`m trying to setup SSO Login with ADFS. I`ve been using the following guide: 
`https://rephlex.de/blog/2018/04/05/how-to-connect-nextcloud-to-active-directory-using-ad-fs-without-losing-your-mind/`

I`ve done everything exactly as that page says, i can authenticate against ADFS using my domain account, but in the end i only get this:

`Account not provisioned.
Your account is not provisioned, access to this service is thus not possible.`

There is nothing on nextcloud.log about this, nor in the ADFS Admin Log. How can i debug and fix this?

Here is my ADFS Configuration, according to that page guide (i didn't erase "classified" information because this machines are strictly LAN only access).

![adfs1](https://user-images.githubusercontent.com/28034970/136665104-97512326-361c-4469-a820-28707062f152.png)
![adfs2](https://user-images.githubusercontent.com/28034970/136665107-4541b9b1-775d-44a3-9e6f-b32e808bd169.png)
![adfs3](https://user-images.githubusercontent.com/28034970/136665111-accff746-fda7-498d-a359-a3a5179d2abd.png)
![adfs4](https://user-images.githubusercontent.com/28034970/136665118-48efcc33-671a-4ce6-8a58-cb8c6232bb0f.png)
![adfs5](https://user-images.githubusercontent.com/28034970/136665122-e00617e7-ab8f-40ab-9c25-03c171082656.png)
![adfs6](https://user-images.githubusercontent.com/28034970/136665127-bea00e30-2b5a-49d6-bdbf-d2be8438e084.png)
![adfs7](https://user-images.githubusercontent.com/28034970/136665132-159dcdf4-91ec-4ca1-adf9-4efd5f312ea8.png)

and my Nextcloud SAML & SSO Settings: 
![nextcloud1](https://user-images.githubusercontent.com/28034970/136665140-87e387c1-e2d7-41f8-9bc6-f3c9c12c4254.png)

**Comment by abctaylor** [comment]
Hi, did you ever solve this or find a configuration that worked for you? I followed the same guide.

**Comment by raulcnadal** [comment]
> Hi, did you ever solve this or find a configuration that worked for you? I followed the same guide.

Hey there!,

I faced this samer issue recently after upgrading ADFS on WS-2019, so I wanted to share how I did sorted it out, jic it can be helpful.

There are different reasons why this can happen, from misconfigured attribute/username mapping to wrong IdP certificate format.

I also followed the same guide mentioned above on this chat, and from a probability PoV,  the latter root cause is most likely the culprit. Wrong signature certificate.

To check what's the real reason of the issue, open another browser session (incognito or open NextCloud admin console from another browser) and go to logging section. Keep it open.

From the other tab you use to test, try to login using ADFS, then check the output on logging section of NC admin console. If it says **signature verification failed**, then you know what's the issue.

If so, easiest way to address it is by using SAML Tracer extension on Chrome to capture the certificate, also with the right format. It's very straightforward to do.

Then paste it "as is" into NextCloud SSO IdP cert field and try ato login gain.

This should short out the issue.

Hope it can be helpful for others,

Thanks,

Kindest Regards,
