### ISSUE TITLE
Facing invalid key type issue while trying to login with user_saml

### ISSUE THREAD

**Issue by Shamri04** [nextcloud/user_saml#765]
Please find the attached log for details:

"Message":"Invalid Key Type","Code":0,"Trace":[{"file":"/data/nextcloud/apps/user_saml/3rdparty/vendor/onelogin/php-saml/src/Saml2/Auth.php","line":739

please help me with this

**Comment by Shamri04** [comment]
Can somebody please  ### **@help?**

**Comment by blizzz** [comment]
Hi @Shamri04,

thank you for getting in touch, and it's great to know that you're interested in using the app. We're using GitHub for discussions related to the code itself and improving the code. To address your particular request more effectively, we recommend utilising other channels better suited for support.

In light of this, and apparently being a configuration matter, I will be closing your issue here. There are alternative avenues for assistance, for example I can recommend our very active [home-user forum](https://help.nextcloud.com) or the [official support channels](https://nextcloud.com/contact). You'll have access to a more suitable platform to discuss and resolve any concerns you may have. Thanks again!
